"""
Legacy office_read_document: Read document structure via Conversion API.

Behavior frozen (§11.2): Word->html, Presentation->txt, Spreadsheet->csv, PDF->txt.
"""

from typing import Any, Callable, Dict, Optional

from aiecs.clients.documentserver_client import DocumentServerClient
from aiecs.tools.office_tool.core.coarse_read import coarse_read_legacy
from aiecs.tools.office_tool.core.storage import ACCEPTED_SOURCE_PATH_FORMATS

OFFICE_READ_DOCUMENT_TOOL = {
    "name": "office_read_document",
    "description": (
        "Read document structure and content. Provide source_path (object storage) OR source_url (HTTP/HTTPS). "
        f"source_path formats: {ACCEPTED_SOURCE_PATH_FORMATS}. "
        "DocumentServer fetches the file via HTTP presigned/signed URL generated by MCP. "
        "Uses Conversion API with LLM-friendly output (Word->html, Presentation->txt, Spreadsheet->csv), "
        "with async polling for large files. Returns elements, word_count, page_count. "
        "IMPORTANT: The index in elements is for logical order only - do NOT use it with "
        "Builder GetElement(index). Use Search(text) or GetStyleName() for positioning in office_edit_document."
    ),
    "inputSchema": {
        "type": "object",
        "properties": {
            "source_path": {
                "type": "string",
                "description": (
                    f"Object storage path. Accepted: {ACCEPTED_SOURCE_PATH_FORMATS}. "
                    "Optional if source_url provided."
                ),
            },
            "source_url": {
                "type": "string",
                "description": "HTTP/HTTPS URL to document. Caller provides fetchable URL. Optional if source_path provided.",
            },
            "format": {
                "type": "string",
                "enum": ["structured", "text", "outline"],
                "default": "structured",
                "description": "structured: full structure; text: plain text; outline: headings only",
            },
        },
        "required": [],
    },
}


async def office_read_document(
    source_path: Optional[str] = None,
    source_url: Optional[str] = None,
    format: str = "structured",
    client: Optional[DocumentServerClient] = None,
) -> Dict[str, Any]:
    """Read document structure via Conversion API (legacy coarse read)."""
    return await coarse_read_legacy(
        source_path=source_path,
        source_url=source_url,
        format=format,
        client=client,
    )


LEGACY_ALIASES: list[tuple[str, Callable[..., Any], dict]] = [
    ("office_read_document", office_read_document, OFFICE_READ_DOCUMENT_TOOL),
]

__all__ = [
    "LEGACY_ALIASES",
    "OFFICE_READ_DOCUMENT_TOOL",
    "office_read_document",
]
